# Generated by Django 4.1.7 on 2023-07-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
