# Generated by Django 4.1.7 on 2023-07-31 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='num',
            new_name='likes',
        ),
    ]
